### ISSUE TITLE
C++ example repo created

### ISSUE THREAD

**Issue by traversaro** [robotology/how-to-export-cpp-library#1]
Hi everybody,
 I have to write a self-contained library for the new algorithm for calibration of FT sensors, so to avoid
rewriting everytime the same structure I tried to set up a reference repo for a typical C++ library.

It is based on https://gitlab.robotology.eu/walkman/template-pkg that uses CMake/YCM, but with some additions (that would be out of scope for Walkman):
- example of use of generated_export_header() cmake macro for correctly exposing symbols and build shared library easily also on Windows,
- example of use of CTest and relative travis/appveyor scripts.

There are still a lot of things to polish/finish, but I guess it can still be a useful reference. 

@francesco-romano @drdanz @arocchi feel free to suggest improvements, even for changes in the 
name of the repo/macros/source code structure. Perhaps Francesco can you add your usual rpath stuff? 

cc @lornat75

**Comment by francesco-romano** [comment]
Added support to RPATH in 8911bb9488b7a3927f196df47baf0a3829a097bd

**Comment by traversaro** [comment]
Just noticed that @lornat75 create an analogous repo in https://github.com/tacman-fp7/template-pkg that shows also how to automatically publish doxygen documentation using gh-pages , I thinks we should merge those changes in this repo (or the other way around) so we can use this for partners that want to distribute libraries (for example people at UPMC).

**Comment by traversaro** [comment]
Updated in 2016.

**Comment by traversaro** [comment]
Interesting things that could be added:  https://gist.github.com/vidavidorra/548ffbcdae99d752da02 .
