### ISSUE TITLE
 Set default CMAKE_BUILD_TYPE 

### ISSUE THREAD

**Issue by traversaro** [robotology/how-to-export-cpp-library#12]
Otherwise, the default build type will be None, with no optimization enabled.
The related code in YARP is the following (from https://github.com/robotology/yarp/blob/9a395f6e41e01d8d350b6a4e5e2b2f6c6f913b74/cmake/YarpOptions.cmake#L69): 
~~~
if(NOT CMAKE_CONFIGURATION_TYPES)
  if(NOT CMAKE_BUILD_TYPE)
    # Encourage user to specify build type.
    message(STATUS "Setting build type to 'Release' as none was specified.")
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY VALUE "Release")
  endif()
endif()
~~~

**Comment by claudiofantacci** [comment]
I'm ok with this.

Actually, I was looking into YARP code for this issue some times ago and I really liked the feature to cycle through different pre-defined configurations. What do you think about it?
My fear is that it may not be suitable for all use cases. Enforcing _Release_, as you suggested, may be a better choice.

**Comment by traversaro** [comment]
The cycle on the possible build types is for populating the HELPSTRING, and that seems an overkill for me, even because I don't really know how to determine all possible `CMAKE_BUILD_TYPE`  possible values.

**Comment by claudiofantacci** [comment]
That's fine even though it would be nice to have "something like that", with a degree of freedom to customize the type as well.

I'll make a PR asap.
