### ISSUE TITLE
Improve doxygen target

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/how-to-export-cpp-library#24]
List of improvements.
- [cmake_format](https://github.com/cheshirekow/cmake_format) configuration style.
- [Change PATH with DIRECTORY.](https://github.com/robotology/how-to-export-cpp-library/pull/22#discussion-diff-168120477R19) PATH is the legacy call for CMake 2.8 which we do not support.
- Give room to doxygen + graphiz (which includes dot executable for generating dependency/inheritance graphs) installation in the README.txt.
- Generate a Doxygen TAG file.

See #22.

**Comment by traversaro** [comment]
**[Added in main issue list]** Generate a Doxygen TAG file

**Comment by claudiofantacci** [comment]
Closing this issue in favour of separated issues.
