### ISSUE TITLE
Add C to project LANGUAGES argument? 

### ISSUE THREAD

**Issue by traversaro** [robotology/how-to-export-cpp-library#25]
In https://github.com/robotology/how-to-export-cpp-library/blob/master/CMakeLists.txt#L26 we only list `CXX` in the LANGUAGES argument of the `project` call. This was done because this template is meant to show how to build a C++ library using CMake. 

However, in the past we had problems with some `Find<package>.cmake` scripts that required the `C` language to be enabled, see for example https://bitbucket.org/ignitionrobotics/ign-cmake/pull-requests/44/fix-findfreeimagecmake-compatibility-with/diff . 

Recently, we had the same problem with the `FindHDF5.cmake` with @pattacini and @vvasco . 
Given that the default setting (when `LANGUAGES` is not specified) is to enable both `CXX` and `C`, and classically `Find<package>.cmake` scripts have been written under those assumptions, I think it is a good idea to add `C` to the `project`  LANGUAGES argument . 

Related bug: https://github.com/robotology/yarp/issues/548 .

**Comment by traversaro** [comment]
cc @drdanz @claudiofantacci

**Comment by claudiofantacci** [comment]
I'm ok with it 😄! Let's add it.

**Comment by claudiofantacci** [comment]
And thanks for the insight! 😲
