### ISSUE TITLE
Any way to modify this for header only libraries ?

### ISSUE THREAD

**Issue by justinjk007** [robotology/how-to-export-cpp-library#28]
Not really header only, but just lot of header files and no target. I tried `add_library(${LIBRARY_TARGET_NAME} INTERFACE)`

but I can't do
```
set_target_properties(${LIBRARY_TARGET_NAME} PROPERTIES VERSION       ${${PROJECT_NAME}_VERSION}
                                                        PUBLIC_HEADER "${${LIBRARY_TARGET_NAME}_HDR}")
```
I can't set the `PUBLIC_HEADER` property so none of the header files are being installed.

**Comment by justinjk007** [comment]
I currently have this, but this won't install the header file https://github.com/hosseinmoein/Matrix/blob/master/CMakeLists.txt

**Comment by claudiofantacci** [comment]
HI @justinjk007 and thanks for reaching out here!

Unofrtunately `INTERFACE` libraries can be installed and exported, but any content they refer to (e.g. the header files) must be installed separately (see also [cmake-buildsystem # interface-libraries](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#interface-libraries)) 😭

You can basically use the same `CMakeLists` you linked before, but you need to specify an `install(FILES)` command to install the headers. Just be careful with the `DESTINATION` path in the `install(FILES)` command that (I reckon) should be the same of the `target_include_directories(<target> INTERFACE)` command that you have deleted for the `INTERFACE` target and was present in our template file.

Let me know if this makes sense to you and if it works and we will sort this out 👍 

I'll thinl/discuss with my colleague if we can broaden our template to header-only targets or if we can add a new folder just for header-only targets.

cc @traversaro @drdanz

**Comment by diegoferigo** [comment]
I recently stumbled upon header-only libraries, you can find a working example in the [robotology/wearable](https://github.com/robotology-playground/wearables/tree/master/interfaces/IWear) repository. Be careful on the directory structure of the project if you want to allow using it from both the build tree and the install tree.

**Comment by justinjk007** [comment]
@claudiofantacci I made these changes https://github.com/justinjk007/Matrix/commit/141c2cb54c83271f996927f61310c80090daeddb on the above cmake file, simply adding an extra install command, which works on linux but dosen't work on Windows. Although it can find the package targets, the header files are not found. I guess i will take a look at what @diegoferigo suggests and get back to you guys.

**Comment by claudiofantacci** [comment]
Hi @justinjk007, I made a fast test and pushed it on [claudio/headeronly](https://github.com/robotology/how-to-export-cpp-library/tree/claudio/headeronly) branch. It seems to be working, but I didn't make extensive tests (and library tests are broken, so leave the option to `OFF`).

Having a look at your `CMakeLists`, it seems to me that you are missing a [target_include_directories()](https://github.com/robotology/how-to-export-cpp-library/blob/f2fbbcb89647a5f42f6f056eb39f472d172ebf36/src/LibTemplateCMake/CMakeLists.txt#L42-L43) and I reckon that `target_sources` is not needed.

Let me know!

**Comment by justinjk007** [comment]
ok so I added these lines and it seems to be able to find the header files now
```
target_include_directories(${LIBRARY_TARGET_NAME} INTERFACE "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>"
                                                            "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/DMScu/include>"
                                                            "$<INSTALL_INTERFACE:$<INSTALL_PREFIX>/${CMAKE_INSTALL_INCLUDEDIR}>"
							    )
```

One thing is, in unix
```
install(FILES "${${LIBRARY_TARGET_NAME}_HDR}"
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/${LIBRARY_TARGET_NAME}"
	)
```
these lines will take effect, where as on windows, the files are never moved around. So on unix those line mean, I can include file from the library in a external project like

`# include <Matrix/Matrix.h>` but that won't work on windows. on Windows only `# include <Matrix.h>` will work. Is there anything in cmake that will make the my include directory behave the same as *nix on windows ? OR do I have to add a Matrix subdir on my libraries include directory ? What's the standard practice ?

also, @diegoferigo 

> Be careful on the directory structure of the project if you want to allow using it from both the build tree and the install tree.

I'm not sure what you mean ?

**Comment by diegoferigo** [comment]
> Is there anything in cmake that will make the my include directory behave the same as *nix on windows ? OR do I have to add a Matrix subdir on my libraries include directory ? What's the standard practice ?

It should be fine as you did. On windows can you check:

1. What is the folder / file structure of your install prefix and check that `include/Matrix/Matrix.h` does exist (as I guess on unix platforms, double check also there)
2. Check on windows what is the include path of the imported target with:
   ```cmake
   get_target_property(VAR ${LIBRARY_TARGET_NAME} INTERFACE_INCLUDE_DIRECTORIES)
   message("${VAR}")
   ```
>> Be careful on the directory structure of the project if you want to allow using it from both the build tree and the install tree.

> I'm not sure what you mean ?

You might want to use your library (i.e. include headers and link targets) with both targets within the same project and targets belonging to an external one (passing through `find_package`). These two case are handled differently, the former uses the so called `BUILD_INTERFACE` and the latter the `INSTALL_INTERFACE`. You can see it from the `target_include_directory` directive. If you want to have the same `#include` in both cases, you should structure your project in such a way that the include path is the same.

Let's clarify this with an example. Imagine you want to: `#include <MyLib/FooComponent/FooHeader.h>`. You project folder should be:

```
project/
├── BarComponent
│   └── .....
└── FooComponent
    ├── include <-- This should be the include of your build interface
    │   └── MyLib
    │       └── FooComponent
    │           └── FooHeader.h
    └── .....
```

When you install the project, you should create the same tree inside your `INSTALL_PREFIX`.

**Comment by claudiofantacci** [comment]
Having a look at your [master branch](https://github.com/justinjk007/Matrix) it seems that the only problem is that, as @diegoferigo explained, that your folder tree structure needs to be rearranged.

In particular, you need to move your headers in a `Matrix` folder that shall be inside the `include` folder. To be honest, I'm surprised that `#include <Matrix/Matrix.h>` is working on *nix system as well.

My suggestion is to have a look at how the folder tree is structuerd in this repository and organize anew you repository to compy with it 😄

**Comment by justinjk007** [comment]
OK I understand what I need to do now, happy to say this https://github.com/justinjk007/Matrix/blob/master/CMakeLists.txt works. I will ofc change the directory structure and make the necessary changes soon.

**Comment by claudiofantacci** [comment]
After this discussion I'll update the repo adding another folder with an `header-only` library template project 👍
