### ISSUE TITLE
Migrate Travis to test on modern Linux distributions?

### ISSUE THREAD

**Issue by traversaro** [robotology/how-to-export-cpp-library#29]
I recently renovated the Travis script for some robotology repos : 
* https://github.com/robotology/robotology-superbuild/pull/108 
* https://github.com/robotology/idyntree/pull/469
* https://github.com/robotology/gazebo-fmi/pull/24

To be honest, I mostly [cargo-culted](https://en.wikipedia.org/wiki/Cargo_cult_programming) the Travis scripts from wb-toolbox and Dart, as discussed in https://github.com/robotology/robotology-superbuild/issues/96 .

I wonder if it could make sense to migrate the Travis template provide in here to run on modern Linux distribution, as the default Trusty distribution shipped by Travis is now 4-years old and not officially supported by the robotology software.

**Comment by claudiofantacci** [comment]
> I wonder if it could make sense to migrate the Travis template provide in here to run on modern Linux distribution, as the default Trusty distribution shipped by Travis is now 4-years old and not officially supported by the robotology software.

Yes. Let's do this asap 👍

**Comment by claudiofantacci** [comment]
Hi @traversaro, I reworked Travis CI a little bit on the branch `feat/travisdistros`, you can have a look at it here [.travis.yml](https://github.com/robotology/how-to-export-cpp-library/blob/feat/travisdistros/.travis.yml). Note that I created _**Bash**_ scripts in a `.ci` folder.

There are pros and cons of using stages like I did in the new Travis file. Definitely is, by my understanding, our only solution if we want to mix multiple Linux distros and macOS builds.

EDIT: We now have gcc and clang on Linux and macOS, just like on master 👍

**Comment by claudiofantacci** [comment]
Relative Travis entry: https://travis-ci.org/robotology/how-to-export-cpp-library/builds/438318541

**Comment by claudiofantacci** [comment]
Travis should be updated to also use `brew` and `apt` addons in place of the standard bash command.

**Comment by traversaro** [comment]
> Travis should be updated to also use brew and apt addons in place of the standard bash command.

Not sure if it make sense to use the `apt` addon, as the packages need to be installed in the guest docker image, not in the host machine.

**Comment by claudiofantacci** [comment]
> Not sure if it make sense to use the `apt` addon, as the packages need to be installed in the guest docker image, not in the host machine.

It does not, indeed, but for up to the current PR, we are still not using dockerised distro images. I just made some working tests on a separate branch (https://github.com/robotology/how-to-export-cpp-library/tree/feat/travisdistros) 😄
