### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/how-to-export-cpp-library#3]
After a major update of the repository (see branch `master` and branch `NoYCM`), I'm bringing back to your attention the discussion about the repository name.

Name proposed so far:

- `how-to-code-cpp-library`
- `how-to-export-library`
- `how-to-export-cpp-library`
- `how-to-export-cpp-library-template`

[Here are](https://github.com/onqtam/awesome-cmake#tutorials--examples--templates) some template names from [Awesome CMake](https://github.com/onqtam/awesome-cmake) repository.
As far as these ones are concerned, I reckon one of either `how-to-export-cpp-library` or `how-to-export-cpp-library-template` is the more appropriate/catchy!

**Comment by traversaro** [comment]
I vote `how-to-export-cpp-library`, as template seems unnecessary if we already have `how-to-etc-etc` in the name.

**Comment by claudiofantacci** [comment]
That is fine for me as well.
