### ISSUE TITLE
Provide hints and useful links on the complexity of mantaining a C++ library  

### ISSUE THREAD

**Issue by traversaro** [robotology/how-to-export-cpp-library#34]
This tutorial simplifies the  process of taking a bunch of C++ classes/functions and expose them as a CMake package, such that third-party code can use it. However, the risk is that new users underestimate the actual complexity of maintaining a C++ library used by many external users. 

A complete and proper training on the art and craft of C++ library maintenance is out of the scope of this repo, but we should at  least add a readme section on this, with possibly some useful links. 

Problems typically overlooked by new C++ library developers: 
* API backward compatibility (as in: be clear about what you promise to users)
* ABI backward compatibility  (as in: be clear about what you promise to users)
* Version handling (semver?)
* Release process
* Etc/etc

**Comment by claudiofantacci** [comment]
This is a very nice hint to improve the repo.
I also think that polishing up the main README is something that must be done in the near future.

Why dont' we start listing some useful references here?

1. [Shared Libraries: Understanding Dynamic Loading](https://amir.rachum.com/blog/2016/09/17/shared-libraries/) 
2. [A successful Git branching model](https://nvie.com/posts/a-successful-git-branching-model/)
3. [SemVer](https://semver.org/)
