### ISSUE TITLE
Typo in RPATH CMake function

### ISSUE THREAD

**Issue by diegoferigo** [robotology/how-to-export-cpp-library#42]
I think here there's a typo:

https://github.com/robotology/how-to-export-cpp-library/blob/e23e399fce102ba8f87cd5269797513000b99794/CMakeLists.txt#L108-L111

It should be:

```cmake
add_install_rpath_support(BIN_DIRS "${CMAKE_INSTALL_FULL_BINDIR}"
                          LIB_DIRS "${CMAKE_INSTALL_FULL_LIBDIR}"
                          INSTALL_NAME_DIR "${CMAKE_INSTALL_FULL_LIBDIR}"
                          USE_LINK_PATH)
```
cc @claudiofantacci @traversaro @drdanz

**Comment by claudiofantacci** [comment]
Good catch @diegoferigo!
Can you please open a PR to fix it?

**Comment by diegoferigo** [comment]
Yes, but there's something more unfortunately, check https://github.com/robotology/ycm/issues/199.

**Comment by claudiofantacci** [comment]
> Yes, but there's something more unfortunately, check [robotology/ycm#199](https://github.com/robotology/ycm/issues/199).

Thanks for pointing me there 👍 However I think that for now the problem is somewhat unrelated and we can proceede with the fix 😄
