### ISSUE TITLE
Missing `BUILD/INSTALL_${TARGET}_INCLUDEDIR` in CMakeLists.txt

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/how-to-export-cpp-library#6]
Some variable are missing before invoking `install_basic_package_files()` in the main CMakeLists.txt (line [#70](https://github.com/robotology/how-to-export-cpp-library/blob/master/CMakeLists.txt#L70)).

In particular, just before line [#70](https://github.com/robotology/how-to-export-cpp-library/blob/master/CMakeLists.txt#L70), a
```cmake
get_property(${PROJECT_NAME}_TARGETS GLOBAL PROPERTY ${PROJECT_NAME}_TARGETS)
```
is missing to properly use the associated global variable.

Furthermore, for `install_basic_package_files()` to work properly, the following 2 variables need to be declared:
```cmake
BUILD_${PROJECT_NAME}_INCLUDEDIR
INSTALL_${PROJECT_NAME}_INCLUDEDIR
```

I have an implementation that seems to work fine, even though it is not a clean solution in the case a user uses `EXTRA_PATH_VARS_SUFFIX`. 

We should briefly discuss a solution when we have some time :-)

**Comment by claudiofantacci** [comment]
cc @drdanz forse puoi aiutarci a venirne a capo!

**Comment by drdanz** [comment]
@claudiofantacci [This](https://gitlab.robotology.eu/walkman/template-pkg/blob/master/src/TemplateLib/CMakeLists.txt#L25) might help...

**Comment by claudiofantacci** [comment]
Indeed, you have to (for example)
~~~cmake
set_property(GLOBAL APPEND PROPERTY ${VARS_PREFIX}_TARGETS template-lib)
~~~
and then
~~~cmake
get_property(${VARS_PREFIX}_TARGETS GLOBAL PROPERTY ${VARS_PREFIX}_TARGETS)
~~~
before invoking `install_basic_package_files()`, which seems to be missing in our main CMakeLists.txt at line [#70](https://github.com/robotology/how-to-export-cpp-library/blob/master/CMakeLists.txt#L70).

But even doing that, the generated `*Config.cmake` file reports
~~~cmake
...
set_and_check(ExportedLib_INCLUDEDIR "")
...
~~~
instead of
~~~cmake
...
set_and_check(AutoCanny_INCLUDEDIR "${PACKAGE_PREFIX_DIR}/include")
...
~~~
To fix this, I also have to
~~~cmake
...
set_property(GLOBAL PROPERTY BUILD_${LIBRARY_TARGET_NAME}_INCLUDEDIR   ${CMAKE_CURRENT_SOURCE_DIR}/include)
set_property(GLOBAL PROPERTY INSTALL_${LIBRARY_TARGET_NAME}_INCLUDEDIR ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_INCLUDEDIR})
...
~~~
in the corresponding LIBRARY_TARGET_NAME `CMakeLists.txt` and lastly, just before invoking `install_basic_package_files()` call
~~~cmake
get_property(BUILD_${LIBRARY_TARGET_NAME}_INCLUDEDIR   GLOBAL PROPERTY BUILD_${LIBRARY_TARGET_NAME}_INCLUDEDIR)
get_property(INSTALL_${LIBRARY_TARGET_NAME}_INCLUDEDIR GLOBAL PROPERTY INSTALL_${LIBRARY_TARGET_NAME}_INCLUDEDIR)
~~~

Have a look [here (main CMakeLists.txt)](https://github.com/claudiofantacci/AutoCanny/blob/master/CMakeLists.txt#L35-L39) and [here (Lib CMakeLists.txt)](https://github.com/claudiofantacci/AutoCanny/blob/master/src/AutoCanny/CMakeLists.txt#L24-L26).

**Comment by Tobias-Fischer** [comment]
Hi @claudiofantacci @drdanz,
I still have this issue. I am using the `how-to-export-cpp-library` example, and in the `./how-to-export-cpp-library/build/LibTemplateCMakeConfig.cmake`, the following line appears:
```
set(LibTemplateCMake_INCLUDEDIR "")
```
So I assume this issue is not yet fixed. You can replicate this issue directly on `master`, I haven't done any modifications.

It would be great if you could have a look into this.

Thanks, Tobi

**Comment by claudiofantacci** [comment]
We actually made a "fix" that also preserved some backward compatibility and that line is the price to pay, @traversaro probably knows best.

The template should work fine, you just need to link your target against `LibTemplateCMake::LibTemplateCMake`. For example, say you have `mytarget` target, then:
```cmake
target_link_libraries(mytarget LibTemplateCMake::LibTemplateCMake)
```
without doing anything else. The other config files take care of the rest.

Let us know if you encounter any other problem or you have suggestions to improve usability and user experience.

**Comment by Tobias-Fischer** [comment]
Hmmm .. sure, I can link to it, but how can I use the header files provided by the library? I.e. how can I `#include "LibTemplateCMake.h"` from an external project?

**Comment by claudiofantacci** [comment]
Includes are part of the `LibTemplateCMake::LibTemplateCMake` target properties.

You can find details in `LibTemplateCMakeTargets.cmake` and in particular in
```cmake
set_target_properties(LibTemplateCMake::LibTemplateCMake PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "<yout_path>/how-to-export-cpp-library/src/LibTemplateCMake/include"
)
```

So when you find the package such includes are already added.

**Comment by Tobias-Fischer** [comment]
Great, get it, working fine, thanks a lot :)!

**Comment by claudiofantacci** [comment]
No worries @Tobias-Fischer, you are welcome :-)

**Comment by Tobias-Fischer** [comment]
I just fully understood how to use this in a dependent project .. for other CMake newbies, this line will do the trick:
`get_target_property(libtemplate_includes LibTemplateCMake::LibTemplateCMake INTERFACE_INCLUDE_DIRECTORIES)`
Then, you can use it as usually:
`include_directories(${CMAKE_CURRENT_SOURCE_DIR} ${libtemplate_includes})`

**Comment by claudiofantacci** [comment]
@Tobias-Fischer that will work, but the pro of using target is to avoid code verbosity and reduce mistakes 😄 
If you use targets, that line can be avoided.

**Comment by Tobias-Fischer** [comment]
Yes, yes .. in that specific code, I needed it for `SWIG` which otherwise does not find the include files. Sorry, should have specified that ;). Otherwise it's not necessary, very true.
